# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if .Values.cloudflare.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  # this is an example of the secret that needs to be created, but w/o the "--sample" suffix
  name: {{ include "cloudflare-tunnel.fullname" . }}--sample
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  TUNNEL_TOKEN: "example-tunnel-token-would-go-here"
{{- end }}
