# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if .Values.cloudflare.existingSecretCred }}
apiVersion: v1
kind: Secret
metadata:
  # this is an example of the secret that needs to be created, but w/o the "--sample" suffix
  name: {{ include "cloudflare-tunnel.fullname" . }}-creds--sample
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag":   "00000000-0000-0000-0000-000000000000",
      "TunnelID":     "00000000-0000-0000-0000-000000000000",
      "TunnelName":   "example-tunnel-name",
      "TunnelSecret": "xxxxxxxxxxxx"
    }
{{- end }}
