# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if not .Values.cloudflare.existingSecretCred }}
# This needs to be created even if tunnelCli is not defined to keep deplyment configs simple
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}-creds
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
{{- if .Values.cloudflare.tunnelCli }}
  credentials.json: |-
    {
      "AccountTag":   {{ .Values.cloudflare.tunnelCli.account    | default "" | quote }},
      "TunnelID":     {{ .Values.cloudflare.tunnelCli.tunnelId   | default "" | quote }},
      "TunnelSecret": {{ .Values.cloudflare.tunnelCli.secret     | default "" | quote }}
    }
{{- else }}
  emptycreds.json: |-
    {}
{{- end }}
{{- end }}
