# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if not .Values.cloudflare.existingSecret }}
# This needs to be created even if tunnelCli is not defined to keep deplyment configs simple
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
{{- if .Values.cloudflare.tunnelToken }}
  TUNNEL_TOKEN: {{ .Values.cloudflare.tunnelToken }}
{{- else }}
  {}
{{- end }}
{{- end }}
